(echo
  (if (eq %isIndexPage% 'yes)
      (script :src "js/jquery-1.10.2.min.js")
    (script :src "../js/jquery-1.10.2.min.js")
  )
  (if (eq %isIndexPage% 'yes)
      (link :rel "stylesheet" :type "text/css" :href "semantic/dist/semantic.min.css")
    (link :rel "stylesheet" :type "text/css" :href "../semantic/dist/semantic.min.css")
  )
  (if (eq %isIndexPage% 'yes)
      (script :src "semantic/dist/semantic.min.js")
    (script :src "../semantic/dist/semantic.min.js")
  )
)
